name: Deploy

on:
  push:
    branches:
      - action
      # - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      repo_lower: ${{ steps.set_env.outputs.repo_lower }}

    steps:
      - uses: actions/checkout@v4

      - name: UPPER to lower
        id: set_env
        run: |
          echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "::set-output name=repo_lower::$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"

      - name: Docker login
        run: echo "${{ secrets.ghrcToken }}" | docker login ghcr.io -u ${{ secrets.ghrcUser }} --password-stdin

      - name: Build and push frontend
        run: |
          touch ./.env
          echo "${{ secrets.ENVFRONT }}" >> ./.env
          docker build -f ./Dockerfile -t ghcr.io/${{ env.repo_lower }}/frontend:latest .
          docker push ghcr.io/${{ env.repo_lower }}/frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/$(whoami)/tiermaster/setup-prod
            echo "${{ secrets.ghrcToken }}" | docker login ghcr.io -u ${{ secrets.ghrcUser }} --password-stdin
            git pull origin main
            docker compose -f compose.yml pull
            docker compose -f compose.yml up -d --remove-orphans
            docker image prune -f
